name: Keneges
description: A new Flutter project A Keneges.uz

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-20.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash: 
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/klogofull.png
  height: 190
  image_dark: assets/images/klogofull.png

flutter:

  uses-material-design: true


  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

