name: Keneges
description: A new Flutter project A Keneges.uz

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-417.4.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.2
  lottie: ^2.3.2 
  google_fonts: ^4.0.4
  fluentui_icons: ^1.0.0
  flutter_native_splash: ^2.3.1
  msix: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash: 
  color: "#f7f6f1"
  color_dark: "#272727"
  image: lib/images/k-logo-full-blue.png
  height: 190
  image_dark: lib/images/k-logo-full-white.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

